export const NEET_2026_SYLLABUS_UNITS = {
  Physics: [
    "Physics and Measurement",
    "Kinematics",
    "Laws of Motion",
    "Work, Energy and Power",
    "Rotational Motion",
    "Gravitation",
    "Properties of Solids and Liquids",
    "Thermodynamics",
    "Kinetic Theory of Gases",
    "Oscillations and Waves",
    "Electrostatics",
    "Current Electricity",
    "Magnetic Effects of Current and Magnetism",
    "Electromagnetic Induction and Alternating Currents",
    "Electromagnetic Waves",
    "Optics",
    "Dual Nature of Matter and Radiation",
    "Atoms and Nuclei",
    "Electronic Devices",
    "Experimental Skills"
  ],
  Chemistry: [
    "Some Basic Concepts of Chemistry",
    "Atomic Structure",
    "Chemical Bonding and Molecular Structure",
    "Chemical Thermodynamics",
    "Solutions",
    "Equilibrium",
    "Redox Reactions and Electrochemistry",
    "Chemical Kinetics",
    "Classification of Elements and Periodicity in Properties",
    "p-Block Elements",
    "d- and f-Block Elements",
    "Coordination Compounds",
    "Purification and Characterisation of Organic Compounds",
    "Some Basic Principles of Organic Chemistry",
    "Hydrocarbons",
    "Organic Compounds Containing Halogens",
    "Organic Compounds Containing Oxygen",
    "Organic Compounds Containing Nitrogen",
    "Biomolecules",
    "Principles Related to Practical Chemistry"
  ],
  Biology: [
    "Diversity in Living World",
    "Structural Organisation in Animals and Plants",
    "Cell Structure and Function",
    "Plant Physiology",
    "Human Physiology",
    "Reproduction",
    "Genetics and Evolution",
    "Biology and Human Welfare",
    "Biotechnology and Its Applications",
    "Ecology and Environment"
  ]
};

export const TOPIC_TO_SYLLABUS_UNITS = {
  Physics: {
    "Units & Dimensions": ["Physics and Measurement", "Experimental Skills"],
    Mechanics: ["Kinematics", "Laws of Motion", "Work, Energy and Power", "Rotational Motion"],
    Gravitation: ["Gravitation"],
    "Waves & SHM": ["Oscillations and Waves"],
    Thermodynamics: ["Thermodynamics", "Kinetic Theory of Gases"],
    Electromagnetism: ["Electrostatics", "Current Electricity", "Magnetic Effects of Current and Magnetism", "Electromagnetic Induction and Alternating Currents"],
    Optics: ["Optics"],
    "Modern Physics": ["Dual Nature of Matter and Radiation", "Atoms and Nuclei", "Electronic Devices"]
  },
  Chemistry: {
    "Mole concept": ["Some Basic Concepts of Chemistry"],
    "Limiting reagent": ["Some Basic Concepts of Chemistry"],
    "Gas laws": ["Some Basic Concepts of Chemistry"],
    pH: ["Equilibrium"],
    Thermochemistry: ["Chemical Thermodynamics"],
    "Equilibrium numericals": ["Equilibrium"],
    Hybridization: ["Chemical Bonding and Molecular Structure"],
    "Bond order": ["Chemical Bonding and Molecular Structure"],
    VBT: ["Chemical Bonding and Molecular Structure"],
    CFT: ["Coordination Compounds"],
    "Periodic trends": ["Classification of Elements and Periodicity in Properties"],
    "Thermal stability trends": ["p-Block Elements", "d- and f-Block Elements"],
    Resonance: ["Some Basic Principles of Organic Chemistry"],
    Hyperconjugation: ["Some Basic Principles of Organic Chemistry"],
    Aromaticity: ["Hydrocarbons"],
    SN1: ["Organic Compounds Containing Halogens"],
    SN2: ["Organic Compounds Containing Halogens"],
    E1: ["Organic Compounds Containing Halogens"],
    E2: ["Organic Compounds Containing Halogens"],
    Lucas: ["Organic Compounds Containing Oxygen"],
    Tollens: ["Organic Compounds Containing Oxygen"],
    Fehling: ["Organic Compounds Containing Oxygen"],
    Aldol: ["Organic Compounds Containing Oxygen"],
    Cannizzaro: ["Organic Compounds Containing Oxygen"]
  },
  Biology: {
    "Cell Division (Mitosis & Meiosis)": ["Cell Structure and Function", "Reproduction"],
    Gametogenesis: ["Reproduction"],
    "Hormones in Reproduction": ["Reproduction", "Human Physiology"],
    "Apomixis & Polyembryony": ["Reproduction"],
    "Development of Male & Female Gametophyte": ["Reproduction"],
    "Contraceptive Methods": ["Reproduction"],
    "Sex Determination": ["Genetics and Evolution"],
    "DNA Structure": ["Genetics and Evolution"],
    Mutations: ["Genetics and Evolution"],
    "Human Genome Project": ["Genetics and Evolution", "Biotechnology and Its Applications"],
    PCR: ["Biotechnology and Its Applications"],
    "Gel Electrophoresis": ["Biotechnology and Its Applications"],
    "DNA Fingerprinting": ["Biotechnology and Its Applications"],
    "rDNA Technology": ["Biotechnology and Its Applications"],
    Operons: ["Genetics and Evolution"],
    "Genetic Disorders": ["Genetics and Evolution"],
    "Hardy-Weinberg Equilibrium": ["Genetics and Evolution"],
    "Homologous vs Analogous Organs": ["Genetics and Evolution"],
    "Evolution of Man": ["Genetics and Evolution"],
    "Light Reaction": ["Plant Physiology"],
    "Dark Reaction (Calvin Cycle)": ["Plant Physiology"],
    "PSI & PSII": ["Plant Physiology"],
    "Cyclic & Non-Cyclic Photophosphorylation": ["Plant Physiology"],
    Photophosphorylation: ["Plant Physiology"],
    "Chemiosmotic Hypothesis": ["Plant Physiology"],
    "Plant Hormones": ["Plant Physiology"],
    "Secondary Growth": ["Structural Organisation in Animals and Plants"],
    "Growth Rates": ["Plant Physiology"],
    "RQ Value": ["Plant Physiology"],
    "Biological Nitrogen Fixation": ["Plant Physiology", "Biology and Human Welfare"],
    "Algae (Life Cycles & Tables)": ["Diversity in Living World"],
    "Mechanism of Breathing": ["Human Physiology"],
    "Respiratory Capacities": ["Human Physiology"],
    "Transport of Gases": ["Human Physiology"],
    "Nerve Impulse Conduction": ["Human Physiology"],
    "Urine Formation": ["Human Physiology"],
    "Mechanism of Hormonal Action": ["Human Physiology"],
    "Nodal Tissue & Cardiac Cycle": ["Human Physiology"],
    ECG: ["Human Physiology"],
    "Blood Clotting & Blood Groups": ["Human Physiology"],
    "Muscle Types": ["Human Physiology"],
    "Mechanism of Muscle Contraction": ["Human Physiology"],
    "Disorders of Human Physiology": ["Human Physiology"],
    "Population Interactions": ["Ecology and Environment"],
    "Ecological Pyramids": ["Ecology and Environment"],
    "Population Growth Curves": ["Ecology and Environment"],
    "Causes of Biodiversity Loss": ["Ecology and Environment"],
    "Microbes in Human Welfare": ["Biology and Human Welfare"],
    Bioreactors: ["Biotechnology and Its Applications"],
    "Tissue Culture & MOET": ["Biotechnology and Its Applications"],
    "BT Toxin (Crops)": ["Biotechnology and Its Applications"],
    Immunity: ["Human Physiology", "Biology and Human Welfare"],
    Antibodies: ["Human Physiology"],
    "Drugs & Drug Abuse": ["Biology and Human Welfare"],
    "Morphology Examples": ["Structural Organisation in Animals and Plants", "Diversity in Living World"],
    "Animal Kingdom (Basis of Classification)": ["Diversity in Living World"],
    "Enzyme Structure & Mechanism": ["Cell Structure and Function"],
    "Enzyme Kinetics": ["Cell Structure and Function"],
    "Inhibition Types": ["Cell Structure and Function"]
  }
};

export const getSyllabusUnitsForTopic = (subject, topic) => {
  const bySubject = TOPIC_TO_SYLLABUS_UNITS[subject] || {};
  return bySubject[topic] || NEET_2026_SYLLABUS_UNITS[subject] || [];
};